version: '3.8'

services:
  madash:
    image: ghcr.io/System-B15/madash/fe:${MADASH_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fe
    restart: unless-stopped
    env_file:
      - .env
    extra_hosts:
      - "hive.org:host-gateway"
    networks:
      - madash_net
      
  websocket:
    image: ghcr.io/System-B15/madash/ws:${MADASH_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile.websocket
    container_name: ws
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - madash_net

  nginx:
    image: ghcr.io/System-B15/madash/proxy:${MADASH_VERSION:-latest}
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - madash
      - websocket
    networks:
      - madash_net

networks:
  madash_net:
    driver: bridge
