services:
  fe:
    image: ghcr.io/system-b15/madash/fe:${MADASH_VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fe
    restart: unless-stopped
    env_file:
      - .env
    extra_hosts:
      - "hive.org:host-gateway"
    networks:
      - madash_net
      
  ws:
    image: ghcr.io/system-b15/madash/ws:${MADASH_VERSION:-latest}
    build:
      context: session-server
      dockerfile: Dockerfile.websocket
    container_name: ws
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - madash_net

  proxy:
    image: ghcr.io/system-b15/madash/proxy:${MADASH_VERSION:-latest}
    container_name: proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fe
      - ws
    networks:
      - madash_net

networks:
  madash_net:
    driver: bridge
